# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding_query.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65mbedding_query.proto\x12\x0f\x65mbedding_query\"!\n\x0e\x45mbeddingQuery\x12\x0f\n\x07queries\x18\x01 \x03(\t\"2\n\x11\x45mbeddingResponse\x12\x1d\n\x15serialized_embeddings\x18\x01 \x01(\x0c\x32h\n\x10\x45mbeddingService\x12T\n\rGetEmbeddings\x12\x1f.embedding_query.EmbeddingQuery\x1a\".embedding_query.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGQUERY']._serialized_start=42
  _globals['_EMBEDDINGQUERY']._serialized_end=75
  _globals['_EMBEDDINGRESPONSE']._serialized_start=77
  _globals['_EMBEDDINGRESPONSE']._serialized_end=127
  _globals['_EMBEDDINGSERVICE']._serialized_start=129
  _globals['_EMBEDDINGSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
