model_list:
  - model_name: qwen2.5-instruct-awq
    litellm_params: 
      model: hosted_vllm/qwen2.5-instruct-awq
      api_base: http://ehr.stalent.cn:53698/v1
      api_key: emma-afa1be76ea27863b3dd72c4eb0f047b8
      rpm: 600
  - model_name: qwen2.5-72b-instruct
    litellm_params:
      model: openai/qwen2.5-72b-instruct # the `openai/` prefix tells litellm it's openai compatible
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-f41ad2c9c0ee48e1a248abcab017942b
      rpm: 1440
  - model_name: qwen-max
    litellm_params:
      model: openai/qwen-max # the `openai/` prefix tells litellm it's openai compatible
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-f41ad2c9c0ee48e1a248abcab017942b
      rpm: 1440
  - model_name: qwen-plus
    litellm_params:
      model: openai/qwen-plus # the `openai/` prefix tells litellm it's openai compatible
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-f41ad2c9c0ee48e1a248abcab017942b
      rpm: 1440
  - model_name: qwen-vl-max
    litellm_params:
      model: openai/qwen-vl-max # the `openai/` prefix tells litellm it's openai compatible
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-f41ad2c9c0ee48e1a248abcab017942b
      rpm: 1440
  - model_name: qwen2-vl-7b-instruct
    litellm_params:
      model: openai/qwen2-vl-7b-instruct # the `openai/` prefix tells litellm it's openai compatible
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-f41ad2c9c0ee48e1a248abcab017942b
      rpm: 1440
  
  # Use this if you want to make requests to `claude-3-haiku-20240307`,`claude-3-opus-20240229`,`claude-2.1` without defining them on the config.yaml
  # Default models
  # Works for ALL Providers and needs the default provider credentials in .env
  - model_name: "*" 
    litellm_params:
      model: "*"

litellm_settings: # module level litellm settings - https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py
  drop_params: True

general_settings: 
  master_key: sk-afa1be76ea27863b3dd72c4eb0f047b8 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)