"""food analyze

Revision ID: 611a0b237900
Revises: e21d60e021c9
Create Date: 2024-12-15 23:43:56.522215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611a0b237900'
down_revision: Union[str, None] = 'e21d60e021c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloom_food_analyze',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('foods', sa.JSON(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('dietary_fiber', sa.Float(), nullable=True),
    sa.Column('vitamin_c', sa.Float(), nullable=True),
    sa.Column('vitamin_d', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('iron', sa.Float(), nullable=True),
    sa.Column('zinc', sa.Float(), nullable=True),
    sa.Column('iodine', sa.Float(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('advice', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bloom_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloom_food_analyze_id'), 'bloom_food_analyze', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bloom_food_analyze_id'), table_name='bloom_food_analyze')
    op.drop_table('bloom_food_analyze')
    # ### end Alembic commands ###
