"""glucose 3

Revision ID: b81147deeb10
Revises: 729d23272a64
Create Date: 2024-11-27 20:27:55.414832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81147deeb10'
down_revision: Union[str, None] = '729d23272a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloom_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('pre_weight', sa.Float(), nullable=False, comment='pre-pregnancy weight(kg)'),
    sa.Column('cur_weight', sa.Float(), nullable=False, comment='current weight(kg)'),
    sa.Column('height', sa.Float(), nullable=False, comment='height(cm)'),
    sa.Column('glucose', sa.Float(), nullable=True, comment='fasting glucose value(mmol/L)'),
    sa.Column('hba1c', sa.Float(), nullable=True, comment='HbA1c(%)'),
    sa.Column('blood_pressure_high', sa.Integer(), nullable=True, comment='blood pressure systolic(mmHg)'),
    sa.Column('blood_pressure_low', sa.Integer(), nullable=True, comment='blood pressure diastolic(mmHg)'),
    sa.Column('gestational_age', sa.Integer(), nullable=False, comment='gestational age'),
    sa.Column('condition', sa.String(length=50), nullable=True, comment='basic disease'),
    sa.Column('condition_level', sa.Integer(), nullable=True, comment='disease level: 1-mild, 2-moderate, 3-severe'),
    sa.Column('complications', sa.String(length=50), nullable=True, comment='complications'),
    sa.Column('exercise_level', sa.Integer(), nullable=True, comment='exercise level: 1-no exercise, 2-less exercise, 3-regular exercise, 4-heavy exercise'),
    sa.Column('prescription', sa.Text(), nullable=True, comment='doctor prescription'),
    sa.Column('dietary_advice', sa.Text(), nullable=True, comment='dietary advice'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bloom_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bloom_glucose', 'measurement_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               postgresql_using='measurement_type::integer',
               comment='type from 1 to 8, representing breakfast before meal, breakfast after meal (2h), lunch before meal, lunch after meal (2h), dinner before meal, dinner after meal (2h), bedtime (around 22-23), midnight (2am)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bloom_glucose', 'measurement_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='type from 1 to 8, representing breakfast before meal, breakfast after meal (2h), lunch before meal, lunch after meal (2h), dinner before meal, dinner after meal (2h), bedtime (around 22-23), midnight (2am)',
               existing_nullable=False)
    op.drop_table('bloom_profiles')
    # ### end Alembic commands ###
